# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blacklight_cql}
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Rochkind"]
  s.date = %q{2011-07-19}
  s.description = %q{May have parts that can be used outside a Blacklight app too with a big of refactoring, let me know if interested.}
  s.email = %q{rochkind@jhu.edu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/blacklight_cql/explain_controller.rb",
    "app/helpers/blacklight_cql/explain_helper.rb",
    "app/views/blacklight_cql/explain/explain.xml.builder",
    "config/routes.rb",
    "lib/blacklight_cql.rb",
    "lib/blacklight_cql/blacklight_to_solr.rb",
    "lib/blacklight_cql/solr_helper_extension.rb",
    "lib/blacklight_cql/template_helper_extension.rb",
    "spec/app_root/app/controllers/application_controller.rb",
    "spec/app_root/config/boot.rb",
    "spec/app_root/config/database.yml",
    "spec/app_root/config/environment.rb",
    "spec/app_root/config/environments/in_memory.rb",
    "spec/app_root/config/environments/mysql.rb",
    "spec/app_root/config/environments/postgresql.rb",
    "spec/app_root/config/environments/sqlite.rb",
    "spec/app_root/config/environments/sqlite3.rb",
    "spec/app_root/config/routes.rb",
    "spec/app_root/lib/blacklight/search_fields.rb",
    "spec/app_root/lib/console_with_fixtures.rb",
    "spec/data/luke.yaml",
    "spec/data/zeerex-2.0.xsd",
    "spec/marc_data/chomsky.mrc",
    "spec/marc_data/social_journal.mrc",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/views/explain.xml.builder_spec.rb",
    "tasks/blacklight_cql_tasks.rake"
  ]
  s.homepage = %q{http://github.com/projectblacklight/blacklight_cql}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Add CQL query support to a Blacklight app}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cql-ruby>, [">= 0.8.1"])
      s.add_development_dependency(%q<markup_validity>, [">= 0"])
    else
      s.add_dependency(%q<cql-ruby>, [">= 0.8.1"])
      s.add_dependency(%q<markup_validity>, [">= 0"])
    end
  else
    s.add_dependency(%q<cql-ruby>, [">= 0.8.1"])
    s.add_dependency(%q<markup_validity>, [">= 0"])
  end
end

